info: |
  Produce a small multiples line chart using d3

scripts:
  - http://d3js.org/d3.v3.min.js

styles:

data_names:
  required:
    - "date"
    - "indexname"
    - "value"
  optional:

default_parameters: {
  width: 960,
  height: 500,
  title: Small Multiples in d3 With clickme
}

require_packages:
  - df2json
  - reshape2

require_server: no

original_url: http://blog.sdqali.in/visualizations/datamyheart/presentation
